In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/zindi-vaccinate/Train (1).csv


In [ ]:
!pip install vaderSentiment

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 4.1 MB/s eta 0:00:00


In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
from pandas import option_context
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier


In [ ]:
df=pd.read_csv("/kaggle/input/zindi-vaccinate/Train (1).csv")
#text_col = "text"
#label_col = "label"

# Later, simpletransformers won't work with str() classes. So let's convert them
# to integers as follows.
#class_dict = {'negative': 0, 'neutral': 1 ,'positive': 2}


#df[label_col] = df["airline_sentiment"].apply(lambda x: class_dict.get(x))
#df.info()


In [ ]:
df.head(2)

tweet_id                                          safe_text  label  \
0  CL1KWCMY  Me &amp; The Big Homie meanboy3000 #MEANBOY #M...    0.0   
1  E3303EME  I'm 100% thinking of devoting my career to pro...    1.0   

   agreement  
0        1.0  
1        1.0

In [ ]:
df.dropna(inplace=True)

In [ ]:
X = df["safe_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y)

In [ ]:
class_dict = {'negative': -1, 'neutral': 0 ,'positive': 1}

In [ ]:
def get_preds(sentences):
  analyzer = SentimentIntensityAnalyzer()
  preds = []
  for sentence in sentences:
      _score = analyzer.polarity_scores(sentence)['compound']
      _class = class_dict.get('neutral')
      if _score <= -0.05:
        _class = class_dict.get('negative')
      elif _score >= 0.05:
        _class = class_dict.get('positive')
      preds.append(_class)
  return preds

y_preds_train_1 = get_preds(X_train)
y_preds_test_1 = get_preds(X_test)

In [ ]:
print(confusion_matrix(y_train, y_preds_train_1))
print(classification_report(y_train, y_preds_train_1))

[[ 301  182  213]
 [1070 1217 1001]
 [1094  689  932]]
              precision    recall  f1-score   support

        -1.0       0.12      0.43      0.19       696
         0.0       0.58      0.37      0.45      3288
         1.0       0.43      0.34      0.38      2715

    accuracy                           0.37      6699
   macro avg       0.38      0.38      0.34      6699
weighted avg       0.47      0.37      0.40      6699



In [ ]:
print(confusion_matrix(y_test, y_preds_test_1))
print(classification_report(y_test, y_preds_test_1))

[[169  89  84]
 [522 590 508]
 [544 351 443]]
              precision    recall  f1-score   support

        -1.0       0.14      0.49      0.21       342
         0.0       0.57      0.36      0.45      1620
         1.0       0.43      0.33      0.37      1338

    accuracy                           0.36      3300
   macro avg       0.38      0.40      0.34      3300
weighted avg       0.47      0.36      0.39      3300

